# Generated by Django 5.2.13 on 2026-04-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('inspiracion', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='perfumes/')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
