# Generated by Django 5.2.13 on 2026-04-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='imagen_original',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/originales/', verbose_name='Foto del perfume original'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/imitaciones/', verbose_name='Foto principal (imitacion)'),
        ),
    ]
