# Generated by Django 5.2.13 on 2026-04-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_perfume_imagen_original_alter_perfume_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acorde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#d4af37', help_text='Color hexadecimal para mostrar el acorde (ej: #ff5733)', max_length=7)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='perfume',
            name='acordes',
            field=models.ManyToManyField(blank=True, related_name='perfumes', to='perfumes.acorde'),
        ),
    ]
