# Generated by Django 5.2.13 on 2026-04-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0003_acorde_perfume_acordes'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='Ingresa cada característica en una línea nueva (Marca, Tipo, Contenido, etc.)'),
        ),
    ]
