# Generated by Django 5.2.13 on 2026-04-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0004_perfume_caracteristicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio en moneda local', max_digits=10),
        ),
    ]
