# Generated by Django 5.2.13 on 2026-04-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0005_perfume_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='precio',
            field=models.IntegerField(default=0, help_text='Precio en CLP (Pesos Chilenos)'),
        ),
    ]
